<?php

namespace Database\Seeders;

use App\Models\Desa;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;


class DesaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('desa')->insert([
            ['nama_desa' => 'Sukodono'],
            ['nama_desa' => 'Pagerkidul'],
            ['nama_desa' => 'Gemaharjo'],
            ['nama_desa' => 'Ploso'],
            ['nama_desa' => 'Donorojo'],
            ['nama_desa' => 'Punung'],
            ['nama_desa' => 'Sidoharjo'],
            ['nama_desa' => 'Dadapan'],
            ['nama_desa' => 'Tanjungsari'],
            ['nama_desa' => 'Arjowinangun'],
            ['nama_desa' => 'Sukoharjo'],
            ['nama_desa' => 'Tegalombo'],
            ['nama_desa' => 'Bangunsari'],
            ['nama_desa' => 'Sumberharjo'],
            ['nama_desa' => 'Mentoro'],
            ['nama_desa' => 'Gondosari'],
            ['nama_desa' => 'Banjarsari'],
            ['nama_desa' => 'Pacitan'],
            ['nama_desa' => ''],
            ['nama_desa' => 'Baleharjo'],
            ['nama_desa' => 'Pagerejo'],
            ['nama_desa' => 'Sooka'],
            ['nama_desa' => 'Bungur'],
            ['nama_desa' => 'Tulakan'],
            ['nama_desa' => 'Purwoasri'],
            ['nama_desa' => 'Pucangsewu'],
            ['nama_desa' => 'Kendal'],
            ['nama_desa' => 'Kayen'],
            ['nama_desa' => 'Wiyoro'],
            ['nama_desa' => 'Nanggungan'],
            ['nama_desa' => 'Pringkuku'],
            ['nama_desa' => 'Mujing'],
            ['nama_desa' => 'Sukorejo'],
            ['nama_desa' => 'Sumberejo'],
            ['nama_desa' => 'Kluwih'],
            ['nama_desa' => 'Temon'],
            ['nama_desa' => 'Wareng'],
            ['nama_desa' => 'Plumbungan'],
            ['nama_desa' => 'Wonoasri'],
            ['nama_desa' => 'Sidomulyo'],
            ['nama_desa' => 'Sirnoboyo'],
            ['nama_desa' => 'Tambakrejo'],
            ['nama_desa' => 'Bogoharjo'],
            ['nama_desa' => 'Karangnongko'],
            ['nama_desa' => 'Ngadirojo'],
            ['nama_desa' => 'Nawangan'],
            ['nama_desa' => 'Banjarjo'],
            ['nama_desa' => 'Widoro'],
            ['nama_desa' => 'Tanjungpuro'],
            ['nama_desa' => 'Gegeran'],
            ['nama_desa' => 'Purworejo'],
            ['nama_desa' => 'Pagerlor'],
            ['nama_desa' => 'Gunungsari'],
            ['nama_desa' => 'Watukarung'],
            ['nama_desa' => 'Arjosari'],
            ['nama_desa' => 'Kebonagung'],
            ['nama_desa' => 'Wonokarto'],
            ['nama_desa' => 'Wonosidi'],
            ['nama_desa' => 'Losari'],
            ['nama_desa' => 'Menadi'],
            ['nama_desa' => 'Bubakan'],
            ['nama_desa' => 'Nogosari'],
            ['nama_desa' => 'Wonogondo'],
            ['nama_desa' => 'Cokrokembang'],
            ['nama_desa' => 'Ngile'],
            ['nama_desa' => 'Kalak'],
            ['nama_desa' => 'Karangrejo'],
            ['nama_desa' => 'Ngadirejan'],
            ['nama_desa' => 'Ketro'],
            ['nama_desa' => 'Sedeng'],
            ['nama_desa' => 'Kasihan'],
            ['nama_desa' => 'Jetak'],
            ['nama_desa' => 'Wonodadi Kulon'],
            ['nama_desa' => 'Tremas'],
            ['nama_desa' => 'Belah'],
            ['nama_desa' => 'Gembong'],
            ['nama_desa' => 'Worawari'],
            ['nama_desa' => 'Nglaran'],
            ['nama_desa' => 'Gendaran'],
            ['nama_desa' => 'Pagutan'],
            ['nama_desa' => 'Tanjunglor'],
            ['nama_desa' => 'Kebondalem'],
            ['nama_desa' => 'Kebonsari'],
            ['nama_desa' => 'Ngromo'],
            ['nama_desa' => 'Bolosingo'],
            ['nama_desa' => 'Gedompol'],
            ['nama_desa' => 'Klesem'],
            ['nama_desa' => 'Kalipelus'],
            ['nama_desa' => 'Gedangan'],
            ['nama_desa' => 'Penggung'],
            ['nama_desa' => 'Jatigunung'],
            ['nama_desa' => 'Gunungrejo'],
            ['nama_desa' => 'Sanggrahan'],
            ['nama_desa' => 'Sedayu'],
            ['nama_desa' => 'Candi'],
            ['nama_desa' => 'Bandar'],
            ['nama_desa' => 'Glinggangan'],
            ['nama_desa' => 'Bomo'],
            ['nama_desa' => 'Kembang'],
            ['nama_desa' => 'Sambong'],
            ['nama_desa' => 'Wonodadi Wetan'],
            ['nama_desa' => 'Dersono'],
            ['nama_desa' => 'Tokawi'],
            ['nama_desa' => 'Pelem'],
            ['nama_desa' => 'Ngunut'],
            ['nama_desa' => 'Jlubang'],
            ['nama_desa' => 'Tahunan'],
            ['nama_desa' => 'Hadiwarno'],
            ['nama_desa' => 'Tamanasri'],
            ['nama_desa' => 'Jeruk'],
            ['nama_desa' => 'Mlati'],
            ['nama_desa' => 'Sudimoro'],
            ['nama_desa' => 'Gasang'],
            ['nama_desa' => 'Sembowo'],
            ['nama_desa' => 'Kalikuning'],
            ['nama_desa' => 'Tinatar'],
            ['nama_desa' => 'Sekar'],
            ['nama_desa' => 'Jatimalang'],
            ['nama_desa' => 'Mendolo Lor'],
            ['nama_desa' => 'Katipugal'],
            ['nama_desa' => 'Sendang'],
            ['nama_desa' => 'Gembuk'],
            ['nama_desa' => 'Karanganyar'],
            ['nama_desa' => 'Petungsinarang'],
            ['nama_desa' => 'Piton'],
            ['nama_desa' => 'Wonoanti'],
            ['nama_desa' => 'Karanggede'],
            ['nama_desa' => 'Ngreco'],
            ['nama_desa' => 'Mantren'],
            ['nama_desa' => 'Ketanggung'],
            ['nama_desa' => 'Kemuning'],
            ['nama_desa' => 'Hadiluwih'],
            ['nama_desa' => 'Tahunan Baru'],
            ['nama_desa' => 'Klepu'],
            ['nama_desa' => 'Gawang'],
            ['nama_desa' => 'Poko'],
            ['nama_desa' => 'Kedungbendo'],
            ['nama_desa' => 'Jetis Lor'],
            ['nama_desa' => 'Ketepung'],
            ['nama_desa' => 'Sempu'],
            ['nama_desa' => 'Semanten'],
            ['nama_desa' => 'Kledung'],
            ['nama_desa' => 'Karangmulyo'],
            ['nama_desa' => 'Padi'],
            ['nama_desa' => 'Gondang'],
            ['nama_desa' => 'Pakis Baru'],
            ['nama_desa' => 'Wonosobo'],
            ['nama_desa' => 'Mendolo Kidul'],
            ['nama_desa' => 'Watupatok'],
            ['nama_desa' => 'Borang'],
            ['nama_desa' => 'Mangunharjo'],
            ['nama_desa' => 'Gayuhan'],
            ['nama_desa' => 'Ponggok'],
            ['nama_desa' => 'Cangkring'],
            ['nama_desa' => 'Punjung'],
            ['nama_desa' => 'Tumpuk'],
            ['nama_desa' => 'Pucangombo'],
            ['nama_desa' => 'Bodag'],
            ['nama_desa' => 'Ngumbul'],
            ['nama_desa' => 'Cemeng'],
            ['nama_desa' => 'Sugihwaras'],
            ['nama_desa' => 'Jetiskidul'],
            ['nama_desa' => 'Sobo'],
            ['nama_desa' => 'Sawahan'],
        ]);
    }
}
